services:
  pihole:
    container_name: ct-pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
    environment:
      TZ: 'Europe/Zurich'
      WEBPASSWORD: ${WEBPASSWORD}
      DNSMASQ_LISTENING: all
      FTLCONF_LOCAL_IPV4: 192.168.1.101
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      WEBTHEME: default-dark
      VIRTUAL_HOST: pihole2.one137.dev
    volumes:
      - '/srv/docker/volumes/pihole/etc-pihole:/etc/pihole'
      - '/srv/docker/volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
