services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: ct-syncthing
    hostname: dockerhost-st
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Zurich
    volumes:
      - /srv/docker/volumes/syncthing/config:/config
      - /srv/docker/volumes/syncthing/data:/data
    # ports:
    #   - 8384:8384
    #   - 22000:22000/tcp
    #   - 22000:22000/udp
    #   - 21027:21027/udp
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    
