services:
  wireguard-client:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: ct-wireguard-client
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Zurich
    volumes:
      - /srv/docker/volumes/wireguard-client:/config
    # ports:
    #   - 52001:52001/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - diun.enable=true
    restart: unless-stopped
