services:
  dnsmasq: # Provides "address=/one137.dev/10.100.0.4" (NPM IP) to wg-easy
    image: 4km3/dnsmasq
    container_name: ct-dnsmasq-wireguard
    cap_add:
      - NET_ADMIN
    networks:
      static:
        ipv4_address: 10.100.0.2
    volumes:
      - /srv/docker/volumes/dnsmasq-wireguard/dnsmasq.conf:/etc/dnsmasq.conf
    restart: unless-stopped

  wireguard-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: ct-wireguard-easy
    depends_on:
      - dnsmasq
    networks:
      static:
        ipv4_address: 10.100.0.3
    volumes:
      - /srv/docker/volumes/wireguard-easy:/etc/wireguard
    # ports:
    #   - "51820:51820/udp"
    #   - "51821:51821/tcp"
    environment:
      - LANG=en
      - WG_HOST=${WG_HOST}
      # Optional:
      - PASSWORD_HASH=${PASSWORD_HASH}
      - WG_PORT=${WG_PORT}
      - WG_DEFAULT_DNS=10.100.0.2 # IP of ct-dnsmasq-wireguard
      - WG_ALLOWED_IPS=192.168.1.0/24, 172.16.0.0/12, 10.8.0.0/16
      - WG_PERSISTENT_KEEPALIVE=30
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=2 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)
      # - PORT=51821
      # - WG_CONFIG_PORT=92820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_MTU=1420
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      # - WG_ENABLE_ONE_TIME_LINKS=true
      # - UI_ENABLE_SORT_CLIENTS=true
      # - WG_ENABLE_EXPIRES_TIME=true
      # - ENABLE_PROMETHEUS_METRICS=false
      # - PROMETHEUS_METRICS_PASSWORD=(see "How_to_generate_an_bcrypt_hash.md" for generate the hash)
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  static:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/24
          gateway: 10.100.0.1
