services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: ct-uptime-kuma
    restart: unless-stopped
    # ports:
    #   - "3001:3001"
    # environment:
    #   PUID: 1001 # Cannot be used for Docker host connection
    #   PGID: 1001
    volumes:
      - /srv/docker/volumes/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro   
